### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by lunalixxi** [TNO/vscode-tracy#55] opened 2023-09-28 14:48 UTC
- [ ] the grey block on the minimap view does not completely cover the width.
![image](https://github.com/TNO/vscode-tracy/assets/23569443/fa956070-aff1-4f22-b2e1-26dafd080337)

**Comment by dennisrd** [comment] 2023-09-29 12:22
I also ran into this problem, but I could not reproduce it. Have you found a detailed recipe how to reproduce?

**Comment by lunalixxi** [comment] 2023-10-02 12:42
> I also ran into this problem, but I could not reproduce it. Have you found a detailed recipe how to reproduce?

After opening the tracy log, you can press several times "ctrl+-", then you will see it.

**Comment by TuenDeBuis** [comment] 2023-10-03 11:54
I think this could be fixed by changing MinimapView.tsx:125 to 
```typescript
ctx.fillRect(0, logScrollTop, max(canvas.width, index*MINIMAP_COLUMN_WIDTH), logEnd - logScrollTop);
```
Though that may just be a temp solution.

**Comment by dennisrd** [comment] 2024-01-25 10:17
The minimap width is now calculated according to the columns that the user has selected to be displayed in the minimap. The issue reported here has not been observed recently, so I will close this.

**Closed by dennisrd** 2024-01-25 10:17 UTC
